Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,6 +27,9 @@ jobs:
       
     - name: Build with gradle
       run: ./gradlew build
+      
+    - name: Debug File System
+      run: ls -l build/libs || echo "build/libs not found!"
 
     - name: Docker Build Push
       uses: mr-smithers-excellent/docker-build-push@v4
